version: '2'
services:
    service-discovery:
        container_name: service-discovery
        build:
            context: .
            dockerfile: Dockerfile.service-discovery
        image:  service-discovery:latest
        entrypoint: ["/bin/bash",  "/home/service/service-discovery-entrypoint.sh"]
        environment:
            APPLICATION_PORT: 8761
            EUREKA_PREFER_IP: 'true'
            EUREKA_SERVER_RESPONSE_CACHE_UPDATE_INTERVAL: 500
            EUREKA_SERVER_EVICTION_INTERVAL: 500
        ports:
            - "8761:8761"
        logging:
            driver: json-file
        networks:
            - service-network
    redis-server:
        container_name: redis-server
        build:
            context: .
            dockerfile: Dockerfile.redis-server
        image:  redis-server:latest
        ports:
            - "6379:6379"
        logging:
            driver: json-file
        networks:
            - service-network
    authentication:
        container_name: authentication
        build:
            context: .
            dockerfile: Dockerfile.authentication
        image:  authentication:latest
        entrypoint: ["/bin/bash",  "/home/service/authentication-entrypoint.sh"]
        depends_on:
            - service-discovery
            - redis-server
            - authentication-db
        environment:
            APPLICATION_PORT: 8500
            DB_HOST: mysql
            DB_PORT: 3306
            EUREKA_HOST: eureka
            EUREKA_PORT: 8761
            EUREKA_PREFER_IP: 'true'
            REDIS_HOST: redis
            REDIS_PORT: 6379
            EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL: 1
            EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION: 2
            EUREKA_CLIENT_INITIAL_REPLICATION_INTERVAL: 0
            EUREKA_CLIENT_REPLICATION_INTERVAL: 1
            EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL: 1
        ports:
            - "8500:8500"
        links:
          - service-discovery:eureka
          - redis-server:redis
          - authentication-db:mysql
        logging:
            driver: json-file
        networks:
            - service-network
    authentication-db:
        image: mysql:5.7.17
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
        volumes:
            # import data upon startup
            - ./binaries/authentication-mysql:/docker-entrypoint-initdb.d
            - authentication-db-volume:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - service-network
    endpoint1:
        container_name: endpoint1
        build:
            context: .
            dockerfile: Dockerfile.endpoint1
        image:  endpoint1:latest
        entrypoint: ["/bin/bash",  "/home/service/endpoint1-entrypoint.sh"]
        depends_on:
            - service-discovery
        environment:
            APPLICATION_PORT: 8085
            EUREKA_HOST: eureka
            EUREKA_PORT: 8761
            EUREKA_PREFER_IP: 'true'
            EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL: 1
            EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION: 2
            EUREKA_CLIENT_INITIAL_REPLICATION_INTERVAL: 0
            EUREKA_CLIENT_REPLICATION_INTERVAL: 1
            EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL: 1
        ports:
            - "8443:8085"
        links:
          - service-discovery:eureka
        logging:
            driver: json-file
        volumes:
          - endpoint1-log-volume:/logs
        networks:
            - service-network
    api-gateway:
        container_name: api-gateway
        build:
            context: .
            dockerfile: Dockerfile.api-gateway
        image:  api-gateway:latest
        entrypoint: ["/bin/bash",  "/home/service/api-gateway-entrypoint.sh"]
        depends_on:
            - service-discovery
        environment:
            EUREKA_HOST: eureka
            EUREKA_PORT: 8761
            EUREKA_PREFER_IP: 'true'
            EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL: 1
            EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION: 2
            EUREKA_CLIENT_INITIAL_REPLICATION_INTERVAL: 0
            EUREKA_CLIENT_REPLICATION_INTERVAL: 1
            EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL: 1
        ports:
            - "8086:8086"
        links:
          - service-discovery:eureka
        logging:
            driver: json-file
        networks:
            - service-network
networks:
    service-network:
        # use the bridge driver
        driver: bridge
volumes:
    authentication-db-volume:
    endpoint1-log-volume: